name: Deploy Action
run-name: ${{ github.actor }} is deploying new version of the bot 🚀
on:
  push:
    main
jobs:
  build-image-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        run: |
          docker build \
            -t bmo6895/book_club_bot:latest \
            --build-arg API_TOKEN="${{ secrets.API_TOKEN }}" \
            --build-arg ADMIN_USER_ID="${{ secrets.ADMIN_USER_ID }}" \
            --build-arg CLUB_CHAT_ID="${{ secrets.CLUB_CHAT_ID }}" \
            .
          docker push bmo6895/book_club_bot:latest
      - name: Download image and restart container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_SECRET_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          username: ${{ secrets.SSH_USERNAME }}
          script: sudo ./bot/full_reboot.sh